# YML是一种文件格式，全称为YAML（YAML Ain't Markup Language），SpringBoot通常使用YML作为项目配置。
# 它是一种人类可读的、简洁明了的数据序列化格式。YAML文件格式通常用于配置文件、数据交换、消息传递和其他应用程序。
# 可以通过文本编辑器进行编辑，也可以通过程序进行解析。YML文件格式是一种以层级缩进的方式表示程序数据结构的格式。
# 在数据表示方面比XML等格式更加简洁清晰易读。YML文件格式通常以“.yml”为扩展名。

# 服务端口
server:
  port: 9281
  servlet:
    context-path: /

# Spring配置
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_hos?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.upload.path}

  # 配置文件上传路径
  mvc:
    static-path-pattern: /uploads/**

# 自定义配置
file:
  upload:
    path: ./uploads/  # 文件上传路径，相对路径（项目根目录下的uploads文件夹）
    base-url: /uploads/  # 文件访问的基础URL

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# Swagger配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.shanzhu.hospital.controller
  openapi:
    info:
      title: 医院管理系统 API文档
      description: 医院管理系统的 API documentation
      version: 1.0.0
      contact:
        name: 开发者
        email: dev@example.com